# Generated by Django 5.0.3 on 2024-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('rangi', models.CharField(max_length=200)),
                ('kattaligi', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('davlati', models.CharField(max_length=200)),
            ],
        ),
    ]
